context:
  name: tombi
  version: "0.6.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tombi-toml/tombi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: adf467a6775d363cd92712c93ed1144c953e73ca1081aa8dcff0b8a8266ab8a3

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - sed -i 's/^\(version[[:space:]]*=[[:space:]]*"\)0\.0\.0-dev\("\)/\1${{ version }}\2/' Cargo.lock
      - sed -i 's/^\(version[[:space:]]*=[[:space:]]*"\)0\.0\.0-dev\("\)/\1${{ version }}\2/' Cargo.toml
      - cd rust/tombi-cli
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - if: unix
      then: sed
      else: m2-sed

tests:
  - script: tombi --help
  - script:
      - if: win
        then: tombi --version | findstr "${{ version }}"
        else: tombi --version | grep -F '${{ version }}'

about:
  homepage: https://tombi-toml.github.io/tombi
  summary: Feature-Rich TOML Toolkit.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://tombi-toml.github.io/tombi/docs
  repository: https://github.com/tombi-toml/tombi

extra:
  recipe-maintainers:
    - janjagusch
